#!/usr/bin/env bash
# One-time per-developer setup: point this machine's Claude Code at the central
# dashboard (telemetry + hooks). Idempotent — safe to re-run. No sudo needed.
#
#   TEAM_ID=stream-mobile \
#   DASHBOARD_URL=https://agents.example.com \
#   INGEST_TOKEN=xxxxx \
#   bash fleet/bootstrap.sh
#
# Then open a new terminal (or `source ~/.config/aad/agent.env`) and run `claude`.
set -euo pipefail

DASHBOARD_URL="${DASHBOARD_URL:-}"
INGEST_TOKEN="${INGEST_TOKEN:-}"
TEAM_ID="${TEAM_ID:-unassigned}"
DEPARTMENT="${DEPARTMENT:-innod}"

if [[ -z "$DASHBOARD_URL" ]]; then
  echo "DASHBOARD_URL is required (e.g. https://agents.example.com)"; exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_SRC="$SCRIPT_DIR/../hooks/hook.js"
AAD_DIR="$HOME/.config/aad"
ENV_FILE="$AAD_DIR/agent.env"
HOOK_DST="$AAD_DIR/hook.js"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

mkdir -p "$AAD_DIR" "$HOME/.claude"

# 1. Copy the hook script to a stable, repo-independent location.
if [[ ! -f "$HOOK_SRC" ]]; then echo "hook.js not found at $HOOK_SRC"; exit 1; fi
cp "$HOOK_SRC" "$HOOK_DST"

# 2. Write the environment file (telemetry + hook config).
cat > "$ENV_FILE" <<EOF
# Agent Activity Dashboard — generated by bootstrap.sh. Do not commit.
export CLAUDE_CODE_ENABLE_TELEMETRY=1
export OTEL_LOGS_EXPORTER=otlp
export OTEL_METRICS_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_PROTOCOL=http/json
export OTEL_EXPORTER_OTLP_ENDPOINT=$DASHBOARD_URL
export OTEL_LOGS_EXPORT_INTERVAL=1000
export OTEL_METRIC_EXPORT_INTERVAL=2000
export OTEL_RESOURCE_ATTRIBUTES="team.id=$TEAM_ID,department=$DEPARTMENT"
$( [[ -n "$INGEST_TOKEN" ]] && echo "export OTEL_EXPORTER_OTLP_HEADERS=\"Authorization=Bearer $INGEST_TOKEN\"" )
# Hooks bridge (ticket/branch + live status):
export AAD_URL=$DASHBOARD_URL
$( [[ -n "$INGEST_TOKEN" ]] && echo "export AAD_TOKEN=$INGEST_TOKEN" )
# NOTE: prompt/tool content logging stays OFF by design — never set
# OTEL_LOG_USER_PROMPTS / OTEL_LOG_TOOL_CONTENT / OTEL_LOG_RAW_API_BODIES.
EOF
echo "wrote $ENV_FILE"

# 3. Source the env file from the shell profile (idempotent).
SOURCE_LINE="[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\"  # agent-activity-dashboard"
for RC in "$HOME/.zshrc" "$HOME/.bashrc"; do
  [[ -e "$RC" ]] || continue
  if ! grep -qF "agent-activity-dashboard" "$RC"; then
    printf '\n%s\n' "$SOURCE_LINE" >> "$RC"
    echo "hooked $ENV_FILE into $RC"
  fi
done

# 4. Merge the six hooks into ~/.claude/settings.json (backup first).
[[ -f "$CLAUDE_SETTINGS" ]] && cp "$CLAUDE_SETTINGS" "$CLAUDE_SETTINGS.bak.$(date +%s)"
HOOK_CMD="node $HOOK_DST" node - "$CLAUDE_SETTINGS" <<'NODE'
const fs = require('fs');
const path = process.argv[2];
const cmd = process.env.HOOK_CMD;
let s = {};
try { s = JSON.parse(fs.readFileSync(path, 'utf8')); } catch {}
s.hooks = s.hooks || {};
const one = [{ hooks: [{ type: 'command', command: cmd }] }];
const withMatcher = [{ matcher: '*', hooks: [{ type: 'command', command: cmd }] }];
const set = (evt, val) => { s.hooks[evt] = val; };
set('SessionStart', one);
set('UserPromptSubmit', one);
set('PreToolUse', withMatcher);
set('PostToolUse', withMatcher);
set('Stop', one);
set('SessionEnd', one);
fs.writeFileSync(path, JSON.stringify(s, null, 2));
console.log('merged hooks into', path);
NODE

echo
echo "Done. team=$TEAM_ID -> $DASHBOARD_URL"
echo "Open a NEW terminal (or 'source $ENV_FILE'), then run 'claude'. Your"
echo "sessions appear on the dashboard as an anonymized agent within '$TEAM_ID'."
